##############################
# http Dockerfile
################################

# Use BlueData base image
FROM bluedata/rhel7

# Install packages with silent (unattended) option
RUN sudo yum -y install httpd
