##############################
# http Dockerfile
################################

# Use BlueData base image 
FROM bluedata/centos7

# Install packages with silent (unattended) option
RUN sudo yum -y install httpd
